=== jppazmin/bibsonomy-social/bibsonomy/bibsonomy-layout/src/main/java/org/bibsonomy/layout/jabref/JabrefLayoutDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

     
     BibSonomy-Layout - Layout engine for the webapp.
      
     Copyright (C) 2006 - 2010 Knowledge & Data Engineering Group, 
                               University of Kassel, Germany
                               http://www.kde.cs.uni-kassel.de/
     
     This program is free software; you can redistribute it and/or
     modify it under the terms of the GNU General Public License
     as published by the Free Software Foundation; either version 2
     of the License, or (at your option) any later version.
    
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

-->

<schema targetNamespace="http://www.bibsonomy.org/resources/xml/JabrefLayoutDefinition" 
		elementFormDefault="qualified" 
		xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:tns="http://www.bibsonomy.org/resources/xml/JabrefLayoutDefinition">
		
	<import
            namespace="http://www.w3.org/XML/1998/namespace"
            schemaLocation="http://www.w3.org/2001/03/xml.xsd"
            />


    <complexType name="JabrefLayout">
    	<annotation>
    		<documentation>Defines one Jabref Layout.</documentation>
    	</annotation>
    	<sequence>
    		<element name="displayName" type="string" maxOccurs="1"
    			minOccurs="1">
    			<annotation>
    				<documentation>
    					The name shown to the user.
    				</documentation>
    			</annotation>
    		</element>
    		<element name="description" maxOccurs="unbounded"
    			minOccurs="1">
    			<annotation>
			    	<documentation>
			    		A short textual description.
			    	</documentation>
			    </annotation>
    			<complexType>
    				<simpleContent>
    					<extension base="string">
    						<attribute ref="xml:lang" use="required"/>
    					</extension>
    				</simpleContent>
    			</complexType>
    		</element>
    		<element name="directory" type="string" maxOccurs="1"
    			minOccurs="0">
    			<annotation>
    				<documentation>
    					If the layout files are in a subdirectory of the
    					layout directory, the name of the directory.
    				</documentation>
    			</annotation>
    		</element>
    		<element name="baseFileName" type="string" maxOccurs="1"
    			minOccurs="1">
    			<annotation>
    				<documentation>
    					The base file name, most often equal to name.
    				</documentation>
    			</annotation>
    		</element>
    		<element name="mimeType" type="string" maxOccurs="1"
    			minOccurs="1">
    			<annotation>
    				<documentation>
    					The mime type of the rendered file.
    				</documentation>
    			</annotation>
    		</element>
    		<element name="extension" type="string" maxOccurs="1"
    			minOccurs="0">
    			<annotation>
    				<documentation>
    					The extension of the rendered file, including
    					the dot.
    				</documentation>
    			</annotation>
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="public" type="boolean" use="optional">
    		<annotation>
    			<documentation>
    				Documents if the layout should be publicly announced
    				on the layout overview page. Making a layout
    				non-public does not prevent other users from using
    				it! Everyone who knows the URL prefix can access the
    				layout.
    			</documentation>
    		</annotation></attribute>
    </complexType>

    <element name="layouts" type="tns:JabrefLayouts"></element>

    <complexType name="JabrefLayouts">
    	<sequence>
    		<element name="layout" type="tns:JabrefLayout" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

</schema>

=== jppazmin/bibsonomy-social/bibsonomy/bibsonomy-layout/src/main/java/org/bibsonomy/layout/jabref/JabrefLayouts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

     
     BibSonomy-Layout - Layout engine for the webapp.
      
     Copyright (C) 2006 - 2010 Knowledge & Data Engineering Group, 
                               University of Kassel, Germany
                               http://www.kde.cs.uni-kassel.de/
     
     This program is free software; you can redistribute it and/or
     modify it under the terms of the GNU General Public License
     as published by the Free Software Foundation; either version 2
     of the License, or (at your option) any later version.
    
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

-->

<layouts
	xmlns="http://www.bibsonomy.org/resources/xml/JabrefLayoutDefinition"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bibsonomy.org/resources/xml/JabrefLayoutDefinition JabrefLayoutDefinition.xsd "
	xmlns:xml="http://www.w3.org/XML/1998/namespace">
	<layout name="html">
		<displayName>HTML</displayName>
		<description xml:lang="en">
			A simple layout where each entry is represented as row in a
			table.
		</description>
		<description xml:lang="de">
			Ausgabe einer einfach formatierten Seite, die Sie in Ihre 
			Homepage einfügen können.
		</description>
		<baseFileName>html</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="simplehtml">
		<displayName>Simple HTML</displayName>
		<description xml:lang="en">
			An HTML layout without any header or footer but very nice
			output. This is useful for integrating publication lists
			into other HTML pages.
		</description>
		<description xml:lang="de">
			Ein HTML-Layout ohne Kopf- und Fußzeile, aber mit einer formatierten Ausgabe.
			Geeignet, um Publikationslisten auf anderen HTML-Seiten einzubetten.
		</description>
		<baseFileName>simplehtml</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="simplehtmlyear">
		<displayName>Simple HTML, grouped by year</displayName>
		<description xml:lang="en">
			An HTML layout without any header or footer but very nice
			output. This is useful for integrating publication lists
			into other HTML pages, grouped by year
		</description>
		<description xml:lang="de">
			Ein HTML-Layout ohne Kopf- und Fußzeile, aber mit einer formatierten Ausgabe.
			Geeignet, um Publikationslisten auf anderen HTML-Seiten einzubetten, gruppiert nach Jahren.
		</description>
		<baseFileName>simplehtmlyear</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="plain">
		<displayName>plain </displayName>
		<description xml:lang="en">
			A simple layout for cvpage
		</description>
		<description xml:lang="de">
			Ausgabe f\u00FCr die cvpage
		</description>
		<baseFileName>plain</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="tablerefs">
		<displayName>HTML table</displayName>
		<description xml:lang="en">
			A more structured HTML output with each entry as a row in a
			table and additional JavaScript search function.
		</description>
		<description xml:lang="de">
			Erzeugt eine strukturierte HTML-Ausgabe, bei der jeder Eintrag in einer Reihe
			innerhalb einer Tabelle dargestellt wird. Die Ausgabe bietet weiterhin Suchfunktionen mittels JavaScript.
		</description>
		<directory>tablerefs</directory>
		<baseFileName>tablerefs</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="tablerefsabsbib">
		<displayName>
			HTML table (with Abstract &amp; BibTeX)
		</displayName>
		<description xml:lang="en">
			Similar to tablerefs but additionally includes the BibTeX
			source and the abstract of the publication.
		</description>
		<description xml:lang="de">
			Ähnlich wie TableRefs, beinhaltet aber zusätzlich den BibTeX Quelltext und
			eine Zusammenfassung der jeweiligen Publikation.
		</description>
		<directory>tablerefsabsbib</directory>
		<baseFileName>tablerefsabsbib</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="tablerefsabsbibsort">
		<displayName>
			HTML table (with Abstract &amp; BibTeX, sortable)
		</displayName>
		<description xml:lang="en">
			Similar to TableRefsAbsBib, but includes possibility to sort
			the table by each column.
		</description>
		<description xml:lang="de">
			Ähnlich wie TableRefsAbsBib, bietet aber zusätzlich die Möglichkeit,
			die Tabelle nach jeder Spalte zu sortieren.
		</description>
		<directory>tablerefsabsbibsort</directory>
		<baseFileName>tablerefsabsbibsort</baseFileName>
		<mimeType>text/html</mimeType>
		<extension>.html</extension>
	</layout>
	<layout name="docbook">
		<displayName>DocBook</displayName>
		<description xml:lang="en">
			This is an XML output according to the DocBook schema.
		</description>
		<description xml:lang="de">
			Liefert eine XML-Ausgabe entsprechend dem DocBook-Schema.
		</description>
		<baseFileName>docbook</baseFileName>
		<mimeType>application/xml</mimeType>
		<extension>.xml</extension>
	</layout>
	<layout name="dblp">
		<displayName>DBLP XML</displayName>
		<description xml:lang="en">
			DBLP export your records to a DBLP conformable XML
			structure.
		</description>
		<description xml:lang="de">
			Exportiert ihre Einträge in einer DBLP-konformen XML-Struktur.
		</description>
		<baseFileName>dblp</baseFileName>
		<mimeType>application/xml</mimeType>
		<extension>.xml</extension>
	</layout>
	<layout name="bibtexml">
		<displayName>BibTeXML</displayName>
		<description xml:lang="en"></description>
		<description xml:lang="de"></description>
		<baseFileName>bibtexml</baseFileName>
		<mimeType>application/xml</mimeType>
		<extension>.xml</extension>
	</layout>
	<layout name="bibordf">
		<displayName>BibO RDF</displayName>
		<description xml:lang="en"></description>
		<description xml:lang="de"></description>
		<baseFileName>bibordf</baseFileName>
		<mimeType>application/rdf+xml</mimeType>
		<extension>.rdf</extension>
	</layout>
	<layout name="harvard">
		<displayName>Harvard RTF</displayName>
		<description xml:lang="en">
			This exports the publication list in Rich Text Format which
			can be used by word processors like OpenOffice or Microsoft
			Word. It is formatted according to the Harvard bibliography
			style guidelines.
		</description>
		<description xml:lang="de">
			Export der Publikationsliste in das Rich Text Format, das von 
			Textverarbeitungsprogrammen wie OpenOffice oder Microsoft verwendet wird. 
			Die Ausgabe wird entsprechend den Harvard-Bibliographie-Richtlinien formatiert. 
		</description>
		<directory>harvard</directory>
		<baseFileName>harvard</baseFileName>
		<mimeType>text/rtf</mimeType>
		<extension>.rtf</extension>
	</layout>
	<layout name="endnote">
		<displayName>EndNote</displayName>
		<description xml:lang="en">
			This is an output in EndNote format which is used by EndNote, another
			bibliography management tool.
		</description>
		<description xml:lang="de">
			Es wird eine Ausgabe in EndNote Format erzeugt, das von EndNote verwendet wird.
			EndNote ist ein weiteres Bibliographie-Werkzeug.
		</description>
		<directory>endnote</directory>
		<baseFileName>EndNote</baseFileName>
		<mimeType>text/plain</mimeType>
		<extension>.txt</extension>
	</layout>
	<layout name="ris_endnote">
		<displayName>RIS (EndNote)</displayName>
		<description xml:lang="en">
			This is an output in RIS which is used by EndNote, another
			bibliography management tool.
		</description>
		<description xml:lang="de">
			Es wird eine Ausgabe im Format RIS erzeugt, das von EndNote verwendet wird.
			EndNote ist ein weiteres Bibliographie-Werkzeug.
		</description>
		<directory>ris_endnote</directory>
		<baseFileName>ris</baseFileName>
		<mimeType>text/plain</mimeType>
		<extension>.txt</extension>
	</layout>
	<layout name="ris_refman">
		<displayName>RIS (ReferenceManager)</displayName>
		<description xml:lang="en">
			This is an output in RIS which is used by ReferenceManager, another
			bibliography management tool.
		</description>
		<description xml:lang="de">
			Es wird eine Ausgabe im Format RIS erzeugt, das vom ReferenceManager verwendet wird.
			ReferenceManager ist ein weiteres Bibliographie-Werkzeug.
		</description>
		<directory>ris_refman</directory>
		<baseFileName>ris</baseFileName>
		<mimeType>text/plain</mimeType>
		<extension>.txt</extension>
	</layout>
	<layout name="openoffice-csv">
		<displayName>OpenOffice CSV</displayName>
		<description xml:lang="en">
			CSV, or Comma Separated Values divides all fields of the
			entry by a comma. It is useful to import the publications
			into spreadsheet programs.
		</description>
		<description xml:lang="de">
			CSV-Dateien ("Komma-separierte Werte") unterteilen alle Felder eines
			Eintrages mit einem Komma. Damit ist es beispielsweise möglich, Publikationen in
			Tabellenkalkulationsprogramme zu importieren.
		</description>
		<directory>openoffice</directory>
		<baseFileName>openoffice-csv</baseFileName>
		<mimeType>text/csv</mimeType>
		<extension>.csv</extension>
	</layout>
	<layout name="text">
		<displayName>Text (BibTeX)</displayName>
		<description xml:lang="en">Another BibTeX output.</description>
		<description xml:lang="de">Erzeugt eine BibTeX-Ausgabe.</description>
		<baseFileName>text</baseFileName>
		<mimeType>text/plain</mimeType>
		<extension>.txt</extension>
	</layout>

	<!-- additional layouts, installed by us -->
